### ISSUE TITLE
Posts uses text to store rich text rather than action_text_rich_texts table

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/main.avodemo.com#6]
I've just noticed that the only place in the demo app that uses a trix field does it an unusual way. I would have expected it to store the rich text in the `action_text_rich_texts` database table, by having a `has_rich_text :body` declaration in the `Post` model, but instead it's using a `text` database field named `body`. That means that Post#body is not an action text field at all, and is rendered quite differently in show pages.

Is that a bug? Or is it deliberate? Does avo support using trix for rich text fields?

**Comment by adrianthedev** [comment]
Hey @iainbeeston. That's correct, the trix field does not use `action_text`. Not sure if it works as expected with `action_text` in this current implementation.

Believe it or not, nobody requested that feature until now (I thought it was going to pop up sooner than this).

Did you try it with `action_text` and it didn't work?

**Comment by iainbeeston** [comment]
I’m using it with action text and it works so far 🤞 I hadn’t realised it could be used with a text area!

**Comment by adrianthedev** [comment]
😂 Ok. Cool! Let us know if something does not work with `action_text`
