### ISSUE TITLE
avodemo.com: login page error messages not obvious

### ISSUE THREAD

**Issue by umaplehurst** [avo-hq/main.avodemo.com#8]
Steps to reproduce:

1. Go to https://main.avodemo.com/
2. Change default pre-filled email address to an invalid address.
3. Now press Sign in button. Login will fail but error message appears at the very bottom of the page and isn't visible unless you scroll down.

**Comment by adrianthedev** [comment]
Hey @umaplehurst.

I think this is a standard devise installation, and Hotwire is not supported correctly without some tweaks.
This is just the demo site, and the authentication issue falls somewhat out of scope.
If one doesn't change the email, things should work properly.

Thanks for writing 🙏

**Comment by umaplehurst** [comment]
Hey @adrianthedev -- any comments / suggestions on what the necessary tweaks would be? I was investigating using the demo site as a starting point for something and came across this issue so thought I should raise the bug. Think it would also help others to hit the ground running if it's something that worked correctly out-of-the-box if you see what I mean? I hope it should be a fairly trivial fix. Thanks!

**Comment by adrianthedev** [comment]
Hmm. Not sure, but I think I'd start by reading these:
 - https://dev.to/efocoder/how-to-use-devise-with-turbo-in-rails-7-9n9
 - https://www.youtube.com/watch?v=yZDTBItc3ZM
 - https://stackoverflow.com/questions/66520254/how-to-display-devise-login-form-errors-when-using-hotwire-rails

I'm open to merging in a PR if we have a fix for them.

**Comment by umaplehurst** [comment]
Many thanks! Will look into those at some point when I get a moment and submit a PR if I come up with something suitable.
